services:
  - type: web
    name: inventory-backend
    runtime: python
    plan: free
    buildCommand: cd Backend && pip install -r requirements.txt
    startCommand: cd Backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        scope: build
        value: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - key: POSTGRES_USER
        scope: build
      - key: POSTGRES_PASSWORD
        scope: build
      - key: POSTGRES_HOST
        scope: build
      - key: POSTGRES_PORT
        scope: build
        value: "5432"
      - key: POSTGRES_DB
        scope: build

  - type: pserv
    name: inventory-db
    runtime: postgres
    plan: free
    ipAllowList: []
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
      - key: POSTGRES_DB
        value: inventory
